POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name":"LV",
    "email": "lv10@gmail.com",
    "password": "lv123456",
    "role": "ADMIN"
}
### 

# @name login
POST http://localhost:3003/user/login
Content-Type: application/json

{
  "email": "eduarda9@gmail.com",
  "password": "123456"
}


###

POST http://localhost:3003/band
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhlMGRmMzhjLTlkMDAtNDhjNC04NjhiLTkyODExNzc4OTQ1MyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1Nzg5MTI0MCwiZXhwIjoxNjU3ODk4NDQwfQ.i3NcPH69Rv2PGXbMiBdCTObyig3wAqLHRn2ldYZyebg

{
    "name": "Coragem",
    "music_genre": "RAP",
    "responsible": "LV"
}

### 

#
GET http://localhost:3003/band?name=Coragem
Content-Type: application/json
